"""Coverage reconciliation engine.

Given Bazarr's "wanted" list, enrich each row with:
- Sonarr/Radarr metadata (originalLanguage, monitored, tags, path)
- Filesystem reality (does any .*.srt already exist next to the file? if so,
  Bazarr's view is stale; flag for scan-disk)
- Tautulli watch-history score (recency + grandparent rewatch signal)

Output is a flat list of CoverageItem dicts. The frontend renders + filters.

Sequential per-source then merge — never blocks on one slow integration
unless every upstream is slow. Each upstream is wrapped in try/except so
a single failure degrades gracefully (the engine returns whatever it
managed to assemble; the response includes a `sources` field showing
which integrations contributed).
"""
from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .config import settings
from .paths import UNSUPPORTED_EXTS
from .integrations import IntegrationError
from .integrations.bazarr import BazarrClient
from .integrations.radarr import RadarrClient
from .integrations.sonarr import SonarrClient
from .integrations.tautulli import TautulliClient

log = logging.getLogger(__name__)


@dataclass
class CoverageItem:
    media_type: str  # "episode" | "movie"
    title: str  # series title (episodes) / movie title
    episode_title: str | None = None
    episode_number: str | None = None  # "1x03"
    original_language: str | None = None
    monitored: bool | None = None
    tags: list[str] = field(default_factory=list)
    # Filesystem reality
    canonical_path: str | None = None  # relative to media_root, parent dir of the video
    has_sub_on_disk: bool = False  # any *.srt next to the video
    sub_files_seen: list[str] = field(default_factory=list)
    # Bazarr cross-reference
    bazarr_sonarr_id: int | None = None
    bazarr_radarr_id: int | None = None
    bazarr_episode_id: int | None = None
    missing_subtitles: list[str] = field(default_factory=list)
    # ffprobe-driven embedded reconciliation (v1.1 batch 1 hotfix)
    embedded_en: str | None = None   # 'EN' / 'EN(forced)' / 'EN(SDH)' / 'EN(commentary)' / None
    audio_langs: list[str] = field(default_factory=list)
    suggest_bazarr_rescan: bool = False
    # Resolved file path (file-level, not series-dir; populated when
    # Sonarr's episode_file is fetched during enrichment)
    file_canonical_path: str | None = None
    # v1.1-B: Sonarr/Radarr's authoritative "we don't have a file yet"
    # signal. When True, Bazarr is asking for subs on a file that hasn't
    # been imported — not actionable, suppress from default queue view.
    pending_download: bool = False
    # v1.1-E: Tautulli reports a Plex session streaming this title now.
    now_playing: bool = False
    # v1.1-I: Sonarr/Radarr imported the file in the last 24h.
    just_imported: bool = False
    # v1.1-H: Sonarr calendar says this airs in the next 48h.
    airing_soon: bool = False
    # v1.1-O: audio language data-quality flags.
    # `audio_label_suspect` = ffprobe says English audio but show is foreign
    #   per Sonarr/Radarr originalLanguage (the encoder probably defaulted
    #   to "eng" without setting the real language).
    # `audio_label_unknown` = ffprobe found no language tag at all ("und")
    #   AND we have no other evidence — needs review or Whisper detection.
    # `audio_label_notes` = human-readable evidence trail for the UI tooltip
    #   ("track 0: tag='eng' but title says 'fre'" / "originalLanguage=Spanish
    #   but audio_langs=['eng']" / etc).
    audio_label_suspect: bool = False
    audio_label_unknown: bool = False
    audio_label_notes: list[str] = field(default_factory=list)
    # v1.1.1 #219: synthetic row generated by the Bazarr-blind defense
    # because Bazarr's wanted view structurally excludes this file (foreign-
    # language series with file metadata claiming English audio). Frontend
    # uses this to render a distinct reason chip ("audio-mislabel-suspect")
    # and surface the upstream fix (set series Language Profile in Sonarr).
    bazarr_blind: bool = False
    # v1.1.1 #219 closer: True once the user verified the audio language
    # for this file. The classifier sets this when the user_verifications
    # lookup hits. Combined with bazarr_blind, the frontend renders a
    # distinct "awaiting Bazarr sync" reason (we propagated to Sonarr but
    # Bazarr's next sync hasn't fired yet) instead of the stale "mislabeled"
    # label that no longer reflects reality.
    audio_verified: bool = False
    # How the audio language was determined, for the UI confidence badge:
    #   "user"    — you verified it (highest trust)
    #   "whisper" — Whisper multi-chunk robust detect
    #   "plex"    — your Plex / Tautulli audio-track pick
    #   "ffprobe" — the file's metadata tag only (lowest trust — wrong on retags)
    #   None      — no confident source (suspect / unknown / no audio)
    audio_source: str | None = None
    # #90: Whisper heard a different language than the file's tag/metadata claimed
    # (e.g. tagged 'rus' but the audio is Korean). Frontend surfaces a
    # "tag → audio (verified)" badge so the mislabel is visible.
    audio_label_whisper_mismatch: bool = False
    # Scoring
    score: int = 0
    score_reasons: list[str] = field(default_factory=list)
    # Probe-gate: has subarr actually analyzed this file?
    #   verified     — a probe matched this row (audio/embedded data resolved)
    #   probe_failed — the file is in probe_failures (couldn't analyze)
    #   unprobed     — no probe + no failure yet (not analyzed)
    #   unsupported  — the resolved file is a disc image / non-video container
    #                  (e.g. a multi-episode .iso) that can't be per-episode
    #                  probed or transcribed — disqualified, not "Analyzing".
    # Only `verified` rows are presented as confident, actionable gaps; the
    # rest are bucketed and held until the probe runs.
    verification_state: str = "unprobed"
    # #79: this file's only English embedded sub is a *forced* track AND the
    # connected subgen has IGNORE_FORCED_SUBTITLES OFF — meaning subgen will
    # SKIP it rather than transcribe a full English sub. Gated on the runtime
    # capability subgen reports via GET /queue (capabilities.ignore_forced_-
    # subtitles). When True this row is a DISTINCT non-actionable state — NOT
    # a normal fillable gap — so the UI can explain "subgen will skip (forced-
    # only); enable IGNORE_FORCED_SUBTITLES" instead of dangling an un-fillable
    # gap. When the cap is on, this stays False and the forced-only row is a
    # normal partial-coverage gap.
    forced_only_subgen_will_skip: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "media_type": self.media_type,
            "title": self.title,
            "episode_title": self.episode_title,
            "episode_number": self.episode_number,
            "original_language": self.original_language,
            "monitored": self.monitored,
            "tags": self.tags,
            "canonical_path": self.canonical_path,
            "has_sub_on_disk": self.has_sub_on_disk,
            "sub_files_seen": self.sub_files_seen,
            "bazarr": {
                "sonarr_id": self.bazarr_sonarr_id,
                "radarr_id": self.bazarr_radarr_id,
                "episode_id": self.bazarr_episode_id,
                "missing_subtitles": self.missing_subtitles,
            },
            "embedded_en": self.embedded_en,
            "audio_langs": self.audio_langs,
            "suggest_bazarr_rescan": self.suggest_bazarr_rescan,
            "file_canonical_path": self.file_canonical_path,
            "pending_download": self.pending_download,
            "now_playing": self.now_playing,
            "just_imported": self.just_imported,
            "airing_soon": self.airing_soon,
            "audio_label_suspect": self.audio_label_suspect,
            "audio_label_unknown": self.audio_label_unknown,
            "audio_label_notes": self.audio_label_notes,
            "bazarr_blind": self.bazarr_blind,
            "audio_verified": self.audio_verified,
            "audio_source": self.audio_source,
            "audio_label_whisper_mismatch": self.audio_label_whisper_mismatch,
            "score": self.score,
            "score_reasons": self.score_reasons,
            "verification_state": self.verification_state,
            "forced_only_subgen_will_skip": self.forced_only_subgen_will_skip,
        }


@dataclass
class CoverageReport:
    generated_at: float
    sources: dict[str, dict[str, Any]]  # name -> {ok: bool, count?: int, error?: str}
    items: list[CoverageItem]

    def to_dict(self) -> dict[str, Any]:
        return {
            "generated_at": self.generated_at,
            "sources": self.sources,
            "items": [i.to_dict() for i in self.items],
            "totals": {
                "items": len(self.items),
                "episodes": sum(1 for i in self.items if i.media_type == "episode"),
                "movies": sum(1 for i in self.items if i.media_type == "movie"),
                "with_disk_sub": sum(1 for i in self.items if i.has_sub_on_disk),
                "embedded_full_en": sum(1 for i in self.items if i.embedded_en == "EN"),
                "suggest_bazarr_rescan": sum(1 for i in self.items if i.suggest_bazarr_rescan),
                # v1.1-B
                "pending_download": sum(1 for i in self.items if i.pending_download),
                "actionable": sum(1 for i in self.items if not i.pending_download),
            },
        }


class IntegrationBundle:
    """Holds the four integration clients + close-all helper. App lifespan
    owns one instance."""

    def __init__(self):
        self.bazarr = BazarrClient()
        self.sonarr = SonarrClient()
        self.radarr = RadarrClient()
        self.tautulli = TautulliClient()
        # v1.1.1: Plex client for partial-scan-on-sidecar-write. Constructed
        # with env-driven config; .is_configured() reflects whether url+token
        # are present so callers degrade gracefully if Plex isn't set up.
        from .integrations.plex import PlexClient
        self.plex = PlexClient(
            base_url=settings.plex_url,
            token=settings.plex_token,
            default_section=settings.plex_section,
            path_prefix=settings.plex_path_prefix,
            media_root=str(settings.media_root),
        )

    async def aclose(self) -> None:
        await asyncio.gather(
            self.bazarr.aclose(),
            self.sonarr.aclose(),
            self.radarr.aclose(),
            self.tautulli.aclose(),
            self.plex.aclose(),
            return_exceptions=True,
        )


# ───────────────────────────── helpers ──────────────────────────────────────


def _strip_arr_prefix(arr_path: str | None) -> str | None:
    """Sonarr returns 'path': '/data/Media/TV/Foo' (its container view).
    Strip the configured prefix to canonical form 'TV/Foo'."""
    if not arr_path:
        return None
    prefix = settings.arr_path_prefix
    s = arr_path
    if prefix and s.startswith(prefix):
        s = s[len(prefix):]
    return s.strip("/")


def _scan_for_srt(canonical_dir: str) -> tuple[bool, list[str]]:
    """Shallow check: does any *.srt exist directly under <media_root>/<canonical>?
    Returns (has_any, list_of_filenames). Best-effort; errors swallowed.

    Kept for the movie path (Radarr's path IS the movie folder, with the
    video + sibling .srt at the same level). For episodes use
    `_scan_for_srt_recursive` + `_match_episode_srt_pattern` because the
    series dir contains Season N/ subfolders the .srt actually lives in.
    """
    if not canonical_dir:
        return False, []
    try:
        full = settings.media_root / Path(canonical_dir)
        if not full.is_dir():
            return False, []
        srts = sorted(p.name for p in full.iterdir() if p.is_file() and p.suffix.lower() == ".srt")
        return bool(srts), srts
    except (OSError, ValueError):
        return False, []


def _scan_for_srt_recursive(canonical_dir: str) -> list[str]:
    """Walk every .srt under <media_root>/<canonical_dir> and return
    relative paths. Cached per series during one coverage build via the
    caller — series with 200 episodes only rglob once.

    Returns relative paths so the caller can match per-episode by looking
    for an S01E03-style substring in the path.
    """
    if not canonical_dir:
        return []
    try:
        full = settings.media_root / Path(canonical_dir)
        if not full.is_dir():
            return []
        return sorted(
            str(p.relative_to(full))
            for p in full.rglob("*.srt")
            if p.is_file()
        )
    except (OSError, ValueError):
        return []


# #104: the per-series rglob is the dominant cost of a coverage build —
# ~668 foreign series each walked one-at-a-time blocked the build for
# minutes. We now fan the rglobs out across a bounded thread pool. The
# cap matters: an UNBOUNDED fan-out would have hundreds of concurrent
# rglobs hammering the NAS at once, which chokes it worse than serial.
# 8-wide is a sane default (matches typical NAS spindle/SMB concurrency
# without thrashing); tune via the call site if needed.
_SRT_SCAN_CONCURRENCY = 8


async def _build_srt_index_parallel(
    canonical_dirs, cap: int = _SRT_SCAN_CONCURRENCY,
) -> dict[str, list[str]]:
    """Recursively scan each (unique, non-empty) series canonical dir for
    .srt files, with bounded concurrency. Returns {canonical_dir: [rel
    srt paths]}. Each dir is scanned exactly once (deduped here), so the
    build's two pass-loops can read straight from the result dict instead
    of awaiting an rglob inline.

    Concurrency is capped via a semaphore so we parallelise the I/O wait
    without unbounded fan-out onto the NAS. Each individual scan still
    runs in a worker thread (rglob is blocking) so the event loop stays
    free."""
    unique = [d for d in dict.fromkeys(canonical_dirs) if d]
    if not unique:
        return {}
    sem = asyncio.Semaphore(max(1, cap))

    async def _one(d: str) -> tuple[str, list[str]]:
        async with sem:
            paths = await asyncio.to_thread(_scan_for_srt_recursive, d)
        return d, paths

    pairs = await asyncio.gather(*[_one(d) for d in unique])
    return dict(pairs)


def _match_episode_srt_pattern(srt_paths: list[str], episode_number: str | None) -> tuple[bool, list[str]]:
    """Given a list of relative .srt paths under a series dir and an
    episode_number ('1x3'), return (any_match, matching_paths).
    Match is case-insensitive S<NN>E<NN> substring in the srt filename.

    FALLBACK PATTERN ONLY — used when Sonarr's authoritative episodeFile.path
    isn't available. Misses release-team naming conventions like 'Part.N',
    'Ep01', 'Episode_3', etc. Prefer `_sidecars_for_file` when the file path
    is known."""
    if not episode_number or "x" not in episode_number or not srt_paths:
        return False, []
    try:
        season, ep = episode_number.split("x")
        pat = f"s{int(season):02d}e{int(ep):02d}"
    except (ValueError, TypeError):
        return False, []
    matches = [p for p in srt_paths if pat in p.lower()]
    return bool(matches), matches


def _sidecars_for_file(srt_paths: list[str], file_canonical: str) -> list[str]:
    """Authoritative sidecar finder: given the actual video file's canonical
    path (e.g. 'TV/Stanley H/Season 1/Stanley.H.Part.1.SUBBED.720p.WEB.h264-WEBTUBE.mkv')
    return every .srt that shares the basename stem.

    Catches Part.N / Episode_NN / 1x1 / arbitrary release naming because we
    match against the actual filename Sonarr says is on disk — no guessing."""
    if not file_canonical or not srt_paths:
        return []
    name = file_canonical.rsplit("/", 1)[-1]
    stem = name.rsplit(".", 1)[0].lower()  # strip extension
    return [p for p in srt_paths if p.rsplit("/", 1)[-1].lower().startswith(stem + ".")
            or p.rsplit("/", 1)[-1].lower() == stem + ".srt"]


def _langs_in_sidecars(sidecars: list[str]) -> set[str]:
    """Parse 2-letter language codes from sidecar filenames.

    Convention: '<basename>.<lang>.srt' (e.g. '...WEBTUBE.en.srt' → 'en').
    Plain '<basename>.srt' → 'und' (undefined; could be anything).
    Tool-suffix forms ('....en.alass.srt', '....en.ffsubsync.srt') are still
    parsed correctly because we grab the lang slot, not the last token."""
    import re
    # [2026-05-30] Split on BOTH dots AND hyphens. Release teams pack
    # the lang code into a hyphen-suffixed cluster ("…x264-iND-en.srt")
    # because they reuse a release-name template. The dot-only splitter
    # in v1.0 missed those because it saw the whole "x264-iND-en" as
    # one token (not alpha → skipped, fell through to "und"). Original
    # subarr handled both separators.
    KNOWN_TOOLS = {"alass", "autosubsync", "ffsubsync", "subsync"}
    # Also skip release-team tokens that look like 2-3 char alpha but
    # AREN'T language codes. Heuristic list — extend as we hit new ones.
    KNOWN_NON_LANG = {"web", "hdtv", "dvd", "uhd", "hdr", "sdr", "ddp",
                       "aac", "dts", "ac3", "flac", "x264", "x265",
                       "ind", "rep", "tla", "ntb", "syn"}

    langs: set[str] = set()
    for p in sidecars:
        name = p.rsplit("/", 1)[-1].lower()
        if not name.endswith(".srt"):
            continue
        # Strip .srt, then split on dots AND hyphens to extract every
        # potential lang-shaped token regardless of separator style.
        tokens = re.split(r"[.\-]", name[:-4])
        found_lang = None
        for tok in reversed(tokens):
            if 2 <= len(tok) <= 3 and tok.isalpha():
                if tok in KNOWN_TOOLS or tok in KNOWN_NON_LANG:
                    continue
                found_lang = tok
                break
        langs.add(found_lang or "und")
    return langs


def _episode_file_canonical(
    sonarr_episode_id: int | None,
    ep_file_paths: dict[int, str],
    sonarr_eps_by_id: dict[int, dict],
) -> str | None:
    """Resolve a wanted episode's actual file to a canonical path via the
    prefetched Sonarr maps (sonarrEpisodeId → episodeFileId → episodeFile
    .path → strip ARR prefix). Returns None when Sonarr has no file for the
    episode (not yet downloaded) — callers must treat that as pending, not
    fabricate a path."""
    if sonarr_episode_id is None:
        return None
    ep = sonarr_eps_by_id.get(sonarr_episode_id) or {}
    ep_file_id = ep.get("episodeFileId")
    abs_path = ep_file_paths.get(ep_file_id) if ep_file_id else None
    if not abs_path:
        return None
    return _strip_arr_prefix(abs_path) or abs_path


def _stale_for_episode(
    *, sonarr_episode_id: int | None,
    ep_file_paths: dict[int, str],
    sonarr_eps_by_id: dict[int, dict],
    series_srt_paths: list[str],
    episode_number: str | None,
    missing_subs: list[str],
) -> tuple[bool, list[str]]:
    """Authoritative stale-disk check.

    1. Resolve sonarrEpisodeId → episodeFileId → episodeFile.path via the
       prefetched maps (no per-call network).
    2. Find every sidecar .srt that shares the file's basename stem.
    3. Stale ONLY if a sidecar matches a WANTED language — an English
       sidecar doesn't satisfy a Dutch wanted row.

    Falls back to S<NN>E<NN> substring match if Sonarr didn't give us a
    file path (episode not yet downloaded, or pre-Sonarr-v3 cluster)."""
    if sonarr_episode_id is None or not series_srt_paths:
        return _match_episode_srt_pattern(series_srt_paths, episode_number) if not missing_subs else (False, [])
    file_canonical = _episode_file_canonical(sonarr_episode_id, ep_file_paths, sonarr_eps_by_id)
    if not file_canonical:
        # No file on disk yet → can't be stale; fall back to pattern only
        # if Bazarr's view might be wrong (rare).
        return _match_episode_srt_pattern(series_srt_paths, episode_number)
    sidecars = _sidecars_for_file(series_srt_paths, file_canonical)
    if not sidecars:
        # [2026-05-30] Basename-stem match failed (common when the
        # video and its .srt come from different release groups —
        # e.g. THESYNDiCATE .mkv with iND-en .srt). Fall back to the
        # S<NN>E<NN> pattern match before declaring no sidecar — the
        # pattern is fuzzier but catches release mismatch. Original
        # subarr behaved this way; the v1.0 rewrite over-tightened.
        ep_pattern_hit, pattern_matches = _match_episode_srt_pattern(
            series_srt_paths, episode_number,
        )
        if not ep_pattern_hit:
            return False, []
        sidecars = pattern_matches
    # [#118] Normalize BOTH sides to canonical ISO-639-1 before comparing — a
    # '.ger.srt'/'.deu.srt' sidecar must satisfy a 'de' wanted, and '.eng.srt'
    # an 'en' wanted. The old raw `[:2]` truncation made 'eng' != 'en' and
    # 'ger'/'deu' un-matchable, raising phantom gaps for langs already on disk.
    from .langs import normalize_lang
    langs_present = {normalize_lang(l) for l in _langs_in_sidecars(sidecars)}
    wanted_codes = {normalize_lang(c) for c in (missing_subs or []) if c}
    # If no missing-subs language list (shouldn't happen for Bazarr wanted
    # rows but be defensive) → any sidecar counts as stale.
    if not wanted_codes:
        return True, sidecars
    # Stale only if at least one sidecar lang matches what's wanted.
    # 'und' (no lang tag) is ambiguous → don't count as stale unless it's
    # the only sidecar; safer to keep showing the gap.
    satisfying = wanted_codes.intersection(langs_present)
    if satisfying:
        return True, sidecars
    return False, sidecars


def _tags_for(arr_record: dict[str, Any], tag_map: dict[int, str]) -> list[str]:
    return sorted(tag_map.get(t, str(t)) for t in (arr_record.get("tags") or []))


# ───────────────────────────── upstream fetches ─────────────────────────────


async def _fetch_bazarr(bz: BazarrClient, sources: dict) -> tuple[list[dict], list[dict]]:
    if not bz.is_configured():
        sources["bazarr"] = {"ok": False, "configured": False}
        return [], []
    try:
        eps_task = asyncio.create_task(bz.episodes_wanted())
        movs_task = asyncio.create_task(bz.movies_wanted())
        eps = await eps_task
        movs = await movs_task
        sources["bazarr"] = {"ok": True, "configured": True,
                             "episodes_wanted": len(eps), "movies_wanted": len(movs)}
        return eps, movs
    except IntegrationError as e:
        sources["bazarr"] = {"ok": False, "configured": True, "error": str(e)}
        return [], []


async def _fetch_arr(name: str, client, sources: dict, fetch_fn: str) -> list[dict]:
    # v1.1-B: parallel fetches share `sources` — merge into existing dict
    # instead of replacing, so a concurrent _fetch_wanted_missing's writes
    # survive whichever task completes last.
    entry = sources.setdefault(name, {})
    if not client.is_configured():
        entry.update({"ok": False, "configured": False})
        return []
    try:
        rows = await getattr(client, fetch_fn)()
        entry.update({"ok": True, "configured": True, "count": len(rows)})
        return rows
    except IntegrationError as e:
        entry.update({"ok": False, "configured": True, "error": str(e)})
        return []


async def _fetch_arr_tags(name: str, client, sources: dict) -> dict[int, str]:
    if not client.is_configured():
        return {}
    try:
        rows = await client.tags()
        return {row["id"]: row.get("label", str(row["id"])) for row in rows}
    except IntegrationError as e:
        # Tag fetch is non-fatal; we just lose tag labels.
        sources.setdefault(name, {}).setdefault("warnings", []).append(f"tags: {e}")
        return {}


async def _fetch_wanted_missing(name: str, client, sources: dict) -> set[int]:
    """v1.1-B: Sonarr/Radarr wanted/missing IDs. Returns empty set if the
    integration isn't configured or the call fails — caller treats missing
    data as "everything is actionable" (degraded but not broken)."""
    if not client.is_configured():
        return set()
    try:
        ids = await client.wanted_missing_ids()
        sources.setdefault(name, {})["wanted_missing"] = len(ids)
        return ids
    except IntegrationError as e:
        sources.setdefault(name, {}).setdefault("warnings", []).append(f"wanted/missing: {e}")
        return set()


async def _fetch_recent_imports(name: str, client, sources: dict) -> set[int]:
    """v1.1-I: arr /history?eventType=3 — files imported in last 24h."""
    if not client.is_configured():
        return set()
    try:
        ids = await client.recent_imports(hours=24)
        sources.setdefault(name, {})["recent_imports_24h"] = len(ids)
        return ids
    except IntegrationError as e:
        sources.setdefault(name, {}).setdefault("warnings", []).append(f"history: {e}")
        return set()


async def _fetch_calendar_upcoming(client, sources: dict) -> set[int]:
    """v1.1-H: Sonarr /calendar — episodes airing within 48h."""
    if not client.is_configured():
        return set()
    try:
        ids = await client.calendar_upcoming(hours=48)
        sources.setdefault("sonarr", {})["airing_within_48h"] = len(ids)
        return ids
    except IntegrationError as e:
        sources.setdefault("sonarr", {}).setdefault("warnings", []).append(f"calendar: {e}")
        return set()


async def _fetch_plex_audio_hints(plex: Any, titles: set[str], sources: dict) -> dict[str, str]:
    """#12: title_lc → per-show selected audio lang from Plex. Best-effort —
    a failure logs into sources['plex'].warnings and returns {} so the
    coverage build is never blocked on Plex."""
    try:
        hints = await plex.audio_lang_hints(titles)
        sources.setdefault("plex", {})["audio_hints"] = len(hints)
        return hints
    except Exception as e:  # noqa: BLE001 — never let Plex break the build
        sources.setdefault("plex", {}).setdefault("warnings", []).append(f"audio_hints: {e}")
        return {}


async def _fetch_tautulli_activity(t: TautulliClient, sources: dict) -> dict:
    """v1.1-E + v1.1-O Layer 2.5: Tautulli get_activity → set of
    grandparent_title (series) currently streaming + subset where Plex is
    transcoding subtitles + per-title audio-track-language hints.

    The audio-track-language hint is gold: when a user picks "French DTS"
    in Plex, that's authoritative ground truth that the audio IS French,
    regardless of what ffprobe's tag says. Stored as
    {title_lc: lang_code} for later cross-check in _classify_audio_label."""
    out = {
        "now_playing_titles": set(),
        "transcoding_titles": set(),
        "audio_lang_hints": {},   # title_lc → 3-letter ISO from user track choice
    }
    if not t.is_configured():
        return out
    try:
        d = await t.get_activity()
        sessions = d.get("sessions") or []
        for s in sessions:
            title = (s.get("grandparent_title") or s.get("full_title") or "").strip().lower()
            if not title:
                continue
            out["now_playing_titles"].add(title)
            if (s.get("subtitle_decision") or "").lower() == "transcode":
                out["transcoding_titles"].add(title)
            # Layer 2.5: audio track language the user actually picked.
            audio_lang = (s.get("stream_audio_language_code")
                          or s.get("audio_language_code") or "").strip().lower()
            if audio_lang and audio_lang not in ("und", ""):
                out["audio_lang_hints"][title] = audio_lang
        sources.setdefault("tautulli", {})["now_playing"] = len(out["now_playing_titles"])
        sources.setdefault("tautulli", {})["audio_hints"] = len(out["audio_lang_hints"])
    except IntegrationError as e:
        sources.setdefault("tautulli", {}).setdefault("warnings", []).append(f"activity: {e}")
    return out


async def _fetch_tautulli(t: TautulliClient, sources: dict) -> list[dict]:
    # v1.1-E: parallel safety — merge not replace (same fix pattern as _fetch_arr).
    entry = sources.setdefault("tautulli", {})
    if not t.is_configured():
        entry.update({"ok": False, "configured": False})
        return []
    try:
        rows = await t.history(length=500, days=30)
        entry.update({"ok": True, "configured": True, "history_rows": len(rows)})
        return rows
    except IntegrationError as e:
        entry.update({"ok": False, "configured": True, "error": str(e)})
        return []


# ───────────────────────────── scoring ──────────────────────────────────────


def _tautulli_signals(history: list[dict]) -> dict[str, dict]:
    """Aggregate history by grandparent (series). Returns
    {grandparent_title_lower: {last_played: epoch, plays_30d: int}}.

    Title-based join because Sonarr ids and Tautulli rating_keys don't
    naturally line up (would need a TVDB↔TMDB↔ratingKey lookup table
    which is v1.2 territory). Title match is lossy but cheap and
    surfaces the obvious wins.
    """
    out: dict[str, dict] = {}
    now = time.time()
    for row in history:
        if row.get("media_type") != "episode":
            continue
        gp = (row.get("grandparent_title") or "").strip().lower()
        if not gp:
            continue
        date = row.get("date") or 0
        agg = out.setdefault(gp, {"last_played": 0, "plays_30d": 0})
        if date > agg["last_played"]:
            agg["last_played"] = date
        if now - date <= 30 * 86400:
            agg["plays_30d"] += 1
    return out


def _episode_filename_pattern(episode_number: str | None) -> str | None:
    """Convert Bazarr's "1x3" → "S01E03" regex pattern for filename matching.
    Returns None if unparseable."""
    if not episode_number or "x" not in episode_number:
        return None
    try:
        season, episode = episode_number.split("x")
        return f"S{int(season):02d}E{int(episode):02d}".lower()
    except (ValueError, TypeError):
        return None


def _attach_probe_episode(item: CoverageItem, idx: dict[str, list],
                          tautulli_hints: dict[str, str] | None = None,
                          user_verifications: dict[str, str] | None = None,
                          failed_idx: dict[str, list] | None = None,
                          plex_hints: dict[str, str] | None = None,
                          whisper_verifications: dict[str, str] | None = None) -> None:
    """Look up a probed file under the series prefix whose basename
    contains S01E03 (or equivalent). On match, copy embedded_en +
    audio_langs + file_canonical_path onto the item and mark it verified.
    On no probe match, mark probe_failed if a probe failure matches the
    same episode, else leave it unprobed (the probe-gate then buckets it)."""
    from .media_probe import audio_lang_summary_with_titles, english_track_summary
    if not item.canonical_path:
        return
    pattern = _episode_filename_pattern(item.episode_number)
    if not pattern:
        return
    for file_canonical, probe in (idx.get(item.canonical_path) or []):
        basename = file_canonical.rsplit("/", 1)[-1].lower()
        if pattern in basename:
            item.file_canonical_path = file_canonical
            item.embedded_en = english_track_summary(probe)
            langs, notes = audio_lang_summary_with_titles(probe)
            item.audio_langs = langs
            if notes:
                item.audio_label_notes.extend(notes)
            _classify_audio_label(item, tautulli_hints=tautulli_hints,
                                  user_verifications=user_verifications,
                                  plex_hints=plex_hints,
                                  whisper_verifications=whisper_verifications)
            item.verification_state = "verified"
            return
    # No successful probe matched — was this episode a probe FAILURE?
    for failed_canonical in ((failed_idx or {}).get(item.canonical_path) or []):
        if pattern in failed_canonical.rsplit("/", 1)[-1].lower():
            item.verification_state = "probe_failed"
            return
    # else: leave default "unprobed"


def _attach_probe_movie(item: CoverageItem, idx: dict[str, list],
                        tautulli_hints: dict[str, str] | None = None,
                        user_verifications: dict[str, str] | None = None,
                        failed_idx: dict[str, list] | None = None,
                        plex_hints: dict[str, str] | None = None,
                        whisper_verifications: dict[str, str] | None = None) -> None:
    """Movies: a single video file lives directly under the movie dir.
    First probe under the movie's canonical wins → verified. No probe but a
    recorded failure → probe_failed. Otherwise unprobed."""
    from .media_probe import audio_lang_summary_with_titles, english_track_summary
    if not item.canonical_path:
        return
    candidates = idx.get(item.canonical_path) or []
    if not candidates:
        if (failed_idx or {}).get(item.canonical_path):
            item.verification_state = "probe_failed"
        return
    file_canonical, probe = candidates[0]
    item.file_canonical_path = file_canonical
    item.embedded_en = english_track_summary(probe)
    langs, notes = audio_lang_summary_with_titles(probe)
    item.audio_langs = langs
    if notes:
        item.audio_label_notes.extend(notes)
    _classify_audio_label(item, tautulli_hints=tautulli_hints,
                          user_verifications=user_verifications,
                          plex_hints=plex_hints,
                          whisper_verifications=whisper_verifications)
    item.verification_state = "verified"


def _classify_audio_label(item: CoverageItem,
                          tautulli_hints: dict[str, str] | None = None,
                          user_verifications: dict[str, str] | None = None,
                          plex_hints: dict[str, str] | None = None,
                          whisper_verifications: dict[str, str] | None = None) -> None:
    """v1.1-O: cross-check audio_langs against Sonarr/Radarr originalLanguage.

    Three outcomes:
    - `audio_label_unknown` = ffprobe found NO language data at all (only "und",
      or empty) → no signal to trust; needs Whisper/review.
    - `audio_label_suspect` = original language is foreign (non-English) but
      every detected audio track is English → likely encoder defaulted to
      "eng" instead of tagging the real language. UI should warn before
      auto-suppressing this row from the queue.
    - Neither flag → either English-original content (expected), or audio
      data agrees with originalLanguage (good).

    Layer 2.5: if Tautulli reports the user picked a specific audio track
    in Plex for this title, that's authoritative — overrides ffprobe entirely
    for the audio_langs field and clears the suspect flag.

    The notes list (already populated by the title-fallback parser) is
    appended to so the UI can show the full evidence trail."""
    # Layer 0 (absolute): user verification beats everything.
    file_path = item.file_canonical_path
    if user_verifications and file_path and file_path in user_verifications:
        from .langs import normalize_lang
        confirmed = user_verifications[file_path]
        prior = [l for l in (item.audio_langs or []) if l and l.lower() not in ("", "und")]
        item.audio_langs = [confirmed]
        note = f"user-confirmed: {confirmed!r}"
        # #90 (C): a verification that disagrees with the file's tag is a
        # mismatch too ("you said X, tag said Y") — show the same dot.
        if prior and normalize_lang(confirmed) not in {normalize_lang(l) for l in prior}:
            note += f" — tags claimed {prior}"
            item.audio_label_whisper_mismatch = True
        item.audio_label_notes.append(note)
        item.audio_label_suspect = False
        item.audio_label_unknown = False
        item.audio_verified = True
        item.audio_source = "user"   # refined to whisper/auto in the post-pass
        return
    # Layer 1 (#90): Whisper-verified spoken language — subarr LISTENED to the
    # audio (robust multi-chunk detect), so it beats tag-derived Plex/Tautulli
    # picks (which inherit the file's mislabel) and the ffprobe tag; it sits
    # below an explicit user confirmation. DORMANT until verifications are
    # supplied (the on-demand trigger is slice 3) → no behaviour change yet.
    if whisper_verifications and file_path and file_path in whisper_verifications:
        from .langs import normalize_lang
        verified = (whisper_verifications[file_path] or "").lower()
        prior = [l for l in (item.audio_langs or []) if l and l.lower() not in ("", "und")]
        item.audio_langs = [verified]
        note = f"Whisper-verified audio = {verified!r} (heard the audio; overrides tags)"
        if prior and verified not in {normalize_lang(l) for l in prior}:
            note += f" — tags claimed {prior}, but the audio is {verified!r}"
            item.audio_label_whisper_mismatch = True
        item.audio_label_notes.append(note)
        item.audio_label_suspect = False
        item.audio_label_unknown = False
        # NOTE: deliberately NOT setting audio_verified — that flag is coupled to
        # USER-propagated-to-Sonarr semantics (drives the "awaiting Bazarr sync"
        # reason, and the frontend badge treats it as 'user'). A machine
        # detection signals via audio_source="whisper" instead, so it badges as
        # the Whisper ✓ tier and never claims a Sonarr propagation it didn't do.
        item.audio_source = "whisper"
        return
    title_lc = (item.title or "").strip().lower()
    if tautulli_hints and title_lc in tautulli_hints:
        plex_lang = tautulli_hints[title_lc]
        # User picked this in Plex → that's the actual audio. Authoritative.
        item.audio_langs = [plex_lang]
        item.audio_label_notes.append(
            f"Plex audio-track pick = {plex_lang!r} (overrides ffprobe)"
        )
        item.audio_label_suspect = False
        item.audio_label_unknown = False
        item.audio_source = "plex"
        return
    # Layer 2.6 (#12): the user's persisted per-show audio pick, read
    # directly from Plex metadata (selected audio stream). Below Tautulli-
    # live (which reflects the freshest in-session choice) but above the
    # ffprobe heuristics. Authoritative when present — same treatment as
    # the Tautulli pick, since both are the user's deliberate Plex choice.
    if plex_hints and title_lc in plex_hints:
        plex_lang = plex_hints[title_lc]
        item.audio_langs = [plex_lang]
        item.audio_label_notes.append(
            f"Plex selected-audio = {plex_lang!r} (per-show pick, overrides ffprobe)"
        )
        item.audio_label_suspect = False
        item.audio_label_unknown = False
        item.audio_source = "plex"
        return
    # [#118] Normalize audio tags to ISO-639-1 so the English-on-foreign-show
    # suspect check below catches eng/en-US, not just the bare 'en'/'eng' forms.
    from .langs import normalize_lang
    langs = [normalize_lang(l) or "und" for l in (item.audio_langs or [])]
    only_und = bool(langs) and all(l in ("", "und") for l in langs)
    no_data = not langs
    if only_und or no_data:
        item.audio_label_unknown = True
        item.audio_label_notes.append(
            "no audio language metadata — encoder didn't tag the stream"
        )
        return
    orig = (item.original_language or "").strip().lower()
    # Foreign originals: anything that isn't English.
    if orig and orig != "english":
        non_und = [l for l in langs if l not in ("", "und")]
        # Suspect when EVERY identified track is English on a foreign show.
        if non_und and all(l == "en" for l in non_und):  # langs are normalized
            item.audio_label_suspect = True
            item.audio_label_notes.append(
                f"originalLanguage={item.original_language!r} but audio tags "
                f"are all English ({non_und}) — likely encoder default"
            )
    # No higher-trust source fired (user/Plex returned early; suspect/unknown
    # set their flags) and we have a usable tag → the language came from the
    # file's ffprobe metadata only. Lowest trust — the UI badge shows it muted.
    if (item.audio_source is None and not item.audio_label_unknown
            and not item.audio_label_suspect
            and any(l not in ("", "und") for l in langs)):
        item.audio_source = "ffprobe"


class _SeriesIntentLookup(dict):
    """A {canonical_path: value} map that, on a miss, falls back to the
    longest series-intent prefix that the looked-up path starts with.

    #69: the coverage build loads verifications in BULK (get_all_as_lookup),
    which deliberately does NOT flatten series intents into one synthetic row
    per episode — that would be O(declared series x episodes) and would go
    stale the instant a new episode is added. Instead we keep the per-file
    rows as the fast exact-match layer and resolve series-intent inheritance
    lazily here. The net effect: a NEW episode under a declared-language
    series auto-resolves as verified during the coverage build, without any
    per-file re-verification — which is exactly the issue's intent.

    Per-file rows always win because dict exact-match short-circuits before
    the prefix fallback ever runs.
    """

    __slots__ = ("_intents",)

    def __init__(self, base: dict, intents: list[tuple[str, str]]):
        super().__init__(base)
        # Longest prefix first so the most specific declaration wins.
        self._intents = sorted(intents, key=lambda t: len(t[0]), reverse=True)

    def __bool__(self) -> bool:
        # Truthy if EITHER per-file rows OR series intents exist — callers
        # guard with `if user_verifications and ...`, and an intents-only
        # store (no per-file rows yet) must still be consulted (#69).
        return bool(len(self) or self._intents)

    def _match_intent(self, key) -> str | None:
        if not isinstance(key, str):
            return None
        for prefix, value in self._intents:
            if key.startswith(prefix):
                return value
        return None

    def __contains__(self, key) -> bool:  # type: ignore[override]
        if super().__contains__(key):
            return True
        return self._match_intent(key) is not None

    def __missing__(self, key):
        value = self._match_intent(key)
        if value is None:
            raise KeyError(key)
        return value

    def get(self, key, default=None):  # type: ignore[override]
        if super().__contains__(key):
            return super().__getitem__(key)
        value = self._match_intent(key)
        return value if value is not None else default


def _build_verification_lookup(audio_lang_store: Any):
    """Build the (user_verifications, verification_sources) pair the coverage
    build feeds to _classify_audio_label / _refine_audio_sources.

    Per-file verifications are the exact-match fast path; declared series
    intents are layered underneath via longest-prefix fallback (#69) so new
    episodes of a declared series inherit the language automatically.
    """
    if audio_lang_store is None:
        return {}, {}
    base_langs = audio_lang_store.get_all_as_lookup()
    base_sources = audio_lang_store.get_all_sources_as_lookup()
    intents = audio_lang_store.list_series_intents()
    lang_intents: list[tuple[str, str]] = [
        (i["series_prefix"], i["lang_code"]) for i in intents
    ]
    # Source string mirrors the per-path get() inheritance label so the UI
    # badge (via _refine_audio_sources -> "user") and any source-aware
    # consumer treats inherited rows as user-sourced.
    source_intents: list[tuple[str, str]] = [
        (i["series_prefix"], f"series_intent:{i.get('source', 'user')}")
        for i in intents
    ]
    user_verifications = _SeriesIntentLookup(base_langs, lang_intents)
    verification_sources = _SeriesIntentLookup(base_sources, source_intents)
    return user_verifications, verification_sources


def _refine_audio_sources(items: list, verification_sources: dict) -> None:
    """Post-pass: _classify set audio_source='user' for any store-verified hit;
    refine it to the ACTUAL verification source so the UI badge distinguishes
    user-verified from machine-detected (Whisper) audio. In place."""
    def _map(raw: str) -> str:
        r = raw.lower()
        if r.startswith("series_intent"):
            return "user"                  # inherited from a user's series declaration
        if "whisper" in r or "auto" in r:
            return "whisper"               # machine multi-chunk detect
        return "user"
    for it in items:
        s = verification_sources.get(it.file_canonical_path)
        if s:
            it.audio_source = _map(s)


def _score(
    item: CoverageItem,
    signals: dict[str, dict],
    *,
    now_playing_titles: set[str] | None = None,
    just_imported_eps: set[int] | None = None,
    just_imported_movies: set[int] | None = None,
    airing_soon_eps: set[int] | None = None,
    transcoding_titles: set[str] | None = None,
    ignore_forced_subtitles: bool = False,
) -> None:
    s = 0
    reasons: list[str] = []
    # v1.1-E: NOW PLAYING boost — strongest signal there is. If Plex is
    # streaming this title RIGHT NOW, queue it.
    title_lc = item.title.strip().lower()
    if now_playing_titles and title_lc in now_playing_titles:
        s += 2000
        reasons.append("PLAYING NOW")
        # v1.1-E++: even stronger if Plex is transcoding subs (CPU burn).
        if transcoding_titles and title_lc in transcoding_titles:
            s += 1000
            reasons.append("Plex transcoding subs — burn signal")
        # Mark for the UI chip
        item.now_playing = True
    # v1.1-I: just imported in last 24h — Sonarr/Radarr say a file just
    # landed; this is when watch likelihood peaks.
    if just_imported_eps and item.bazarr_episode_id in just_imported_eps:
        s += 800
        reasons.append("just imported (<24h)")
        item.just_imported = True
    elif just_imported_movies and item.bazarr_radarr_id in just_imported_movies:
        s += 800
        reasons.append("just imported (<24h)")
        item.just_imported = True
    # v1.1-H: airs within 48h — pre-warm the queue so subs are ready when
    # the episode hits disk.
    if airing_soon_eps and item.bazarr_episode_id in airing_soon_eps:
        s += 400
        reasons.append("airs within 48h")
        item.airing_soon = True
    sig = signals.get(title_lc)
    if sig:
        age_days = (time.time() - sig["last_played"]) / 86400.0 if sig["last_played"] else 9999
        if age_days <= 7:
            s += 1000
            reasons.append(f"watched in last 7d ({age_days:.0f}d)")
        elif age_days <= 30:
            s += 500
            reasons.append(f"watched in last 30d ({age_days:.0f}d)")
        if sig["plays_30d"] > 3:
            s += 200
            reasons.append(f"{sig['plays_30d']} plays in 30d")
    if item.original_language and item.original_language.lower() != "english":
        s += 100
        reasons.append(f"non-english ({item.original_language})")
    if item.monitored:
        s += 50
        reasons.append("monitored")
    if item.has_sub_on_disk:
        # Strong negative — disk has a sub, Bazarr's view is stale. Flip
        # suggest_bazarr_rescan too so the UI can offer the →Bazarr action
        # (the existing /api/bazarr/sync-disk endpoint).
        s -= 5000
        reasons.append("stale: disk already has .srt (Bazarr needs scan-disk)")
        item.suggest_bazarr_rescan = True
    # v1.1 hotfix + 2026-05-27 SDH collapse: SDH counts the same as a
    # clean English track for scoring purposes (an SDH track IS English).
    # Forced + commentary tracks remain partial (those genuinely aren't
    # full subs for the show).
    if item.embedded_en in {"EN", "EN(SDH)"}:
        s -= 3000
        label = "full English" if item.embedded_en == "EN" else "English SDH"
        reasons.append(f"embedded: {label} sub in file (Bazarr missed it)")
        item.suggest_bazarr_rescan = True
    elif item.embedded_en in {"EN(forced)", "EN(commentary)"}:
        s -= 500
        reasons.append(f"embedded: {item.embedded_en} — partial coverage")
        # #79: forced-only EN is only an ACTIONABLE gap if the connected
        # subgen will actually fill it (IGNORE_FORCED_SUBTITLES on). With the
        # cap off, subgen SKIPS forced-only files — so flag a distinct,
        # non-actionable state + reason instead of dangling an un-fillable gap.
        # The cap governs FORCED subs only; commentary tracks are untouched.
        if item.embedded_en == "EN(forced)" and not ignore_forced_subtitles:
            item.forced_only_subgen_will_skip = True
            reasons.append(
                "subgen will skip this (forced-only EN) — "
                "enable IGNORE_FORCED_SUBTITLES on subgen to transcribe it"
            )
    item.score = s
    item.score_reasons = reasons


# ───────────────────────────── main entrypoint ──────────────────────────────


def _disqualify_unsupported(items: list[CoverageItem]) -> None:
    """#96/#62: mark disc-image / non-video containers (e.g. a multi-episode
    .iso, which resolves via Sonarr's episodeFile to one disc path for every
    episode it holds) as 'unsupported' — ffprobe can't give per-episode audio
    and subgen can't transcribe it per-episode, so it can never become a real
    gap. This drops it OUT of the "Analyzing" bucket (where it would sit
    forever, since the probe walker skips non-video extensions) instead of
    presenting it as actionable. Folders / unresolved files are a SEPARATE
    resolution gap and intentionally untouched. Already-verified rows are left
    alone. Mutates in place."""
    for it in items:
        if it.verification_state == "verified":
            continue
        cand = it.file_canonical_path or it.canonical_path or ""
        if cand and Path(cand).suffix.lower() in UNSUPPORTED_EXTS:
            it.verification_state = "unsupported"


async def build_coverage(
    bundle: IntegrationBundle,
    *,
    use_tautulli: bool = True,
    probe_store: Any = None,  # ProbeStore | None — avoid circular import
    audio_lang_store: Any = None,  # AudioLangStore | None
    subgen_caps: Any = None,  # SubgenCapabilities | None — #79 forced-sub gate
) -> CoverageReport:
    sources: dict[str, dict] = {}
    # #79: gate the forced-only-EN partial gap on subgen's RUNTIME
    # IGNORE_FORCED_SUBTITLES. caps absent / cap off → forced-only EN rows are
    # marked forced_only_subgen_will_skip (distinct non-actionable state) rather
    # than presented as fillable gaps. caps on → they stay actionable gaps.
    ignore_forced = bool(getattr(subgen_caps, "ignore_forced_subtitles", False))

    bz_eps, bz_movs = await _fetch_bazarr(bundle.bazarr, sources)
    sonarr_series_task = asyncio.create_task(
        _fetch_arr("sonarr", bundle.sonarr, sources, "series")
    )
    radarr_movies_task = asyncio.create_task(
        _fetch_arr("radarr", bundle.radarr, sources, "movies")
    )
    sonarr_tags_task = asyncio.create_task(_fetch_arr_tags("sonarr", bundle.sonarr, sources))
    radarr_tags_task = asyncio.create_task(_fetch_arr_tags("radarr", bundle.radarr, sources))
    # v1.1-B: wanted/missing sets — "no file imported yet" authoritative truth.
    sonarr_missing_task = asyncio.create_task(_fetch_wanted_missing("sonarr", bundle.sonarr, sources))
    radarr_missing_task = asyncio.create_task(_fetch_wanted_missing("radarr", bundle.radarr, sources))
    # v1.1-I: recent imports (<24h) — high-likelihood watch targets.
    sonarr_recent_task = asyncio.create_task(_fetch_recent_imports("sonarr", bundle.sonarr, sources))
    radarr_recent_task = asyncio.create_task(_fetch_recent_imports("radarr", bundle.radarr, sources))
    # v1.1-H: calendar upcoming (<48h) — pre-warm the queue.
    sonarr_calendar_task = asyncio.create_task(_fetch_calendar_upcoming(bundle.sonarr, sources))
    # v1.1-E: NOW PLAYING via Tautulli get_activity.
    tautulli_activity_task = (
        asyncio.create_task(_fetch_tautulli_activity(bundle.tautulli, sources))
        if use_tautulli else None
    )
    tautulli_task = (
        asyncio.create_task(_fetch_tautulli(bundle.tautulli, sources))
        if use_tautulli else None
    )

    sonarr_series = await sonarr_series_task
    radarr_movies = await radarr_movies_task
    sonarr_tags = await sonarr_tags_task
    radarr_tags = await radarr_tags_task
    sonarr_missing_ids = await sonarr_missing_task   # set[int]
    radarr_missing_ids = await radarr_missing_task   # set[int]
    sonarr_recent_ids = await sonarr_recent_task     # set[int]
    radarr_recent_ids = await radarr_recent_task     # set[int]
    airing_soon_ids = await sonarr_calendar_task     # set[int]
    history = await tautulli_task if tautulli_task else []
    activity = await tautulli_activity_task if tautulli_activity_task else {"now_playing_titles": set(), "transcoding_titles": set()}

    # #12: per-show selected audio language from Plex (opt-in, funnel L2.6,
    # below Tautulli-live). Show-level signal → episodes only. Best-effort:
    # never breaks the build. Cached on the Plex client across builds.
    plex_audio_hints: dict[str, str] = {}
    if settings.plex_audio_hints and bundle.plex.is_configured():
        ep_titles = {(w.get("seriesTitle") or "") for w in bz_eps}
        plex_audio_hints = await _fetch_plex_audio_hints(bundle.plex, ep_titles, sources)

    sonarr_by_id = {s["id"]: s for s in sonarr_series if isinstance(s, dict) and "id" in s}
    radarr_by_title = {m.get("title", "").strip().lower(): m
                       for m in radarr_movies if isinstance(m, dict)}
    tt_signals = _tautulli_signals(history) if history else {}

    # Probe-cache index: { series_canonical_prefix → [(file_canonical, ProbeResult)] }
    # Pre-build once so per-row lookup is O(files-under-this-series) not O(total-cache).
    probe_by_series_prefix: dict[str, list[tuple[str, Any]]] = {}
    if probe_store is not None:
        sources["probe_cache"] = {"ok": True, "entries": 0}
        for path in probe_store.all_paths():
            entry = probe_store.get(path)  # non-strict — accept whatever's cached
            if entry is None:
                continue
            sources["probe_cache"]["entries"] += 1
            # Index under all ancestor prefixes so a single all-series cache scan
            # finds matches for any series-level Bazarr row.
            parts = path.split("/")
            for i in range(2, len(parts)):  # skip top-level (TV/Movies)
                prefix = "/".join(parts[:i])
                probe_by_series_prefix.setdefault(prefix, []).append((path, entry))

    # Probe-FAILURE index (same prefix scheme). Rows whose file is recorded
    # as a probe failure get tagged probe_failed rather than appearing as an
    # un-flagged gap that subgen would then skip.
    probe_failed_by_prefix: dict[str, list[str]] = {}
    if probe_store is not None:
        failed = probe_store.failed_paths()
        if failed and "probe_cache" in sources:
            sources["probe_cache"]["failures"] = len(failed)
        for path in failed:
            parts = path.split("/")
            for i in range(2, len(parts)):
                prefix = "/".join(parts[:i])
                probe_failed_by_prefix.setdefault(prefix, []).append(path)

    # #69 + #90 reconciled: build the intent-aware verification lookup (series-
    # intent prefix fallback so NEW episodes of a declared-language series
    # auto-resolve as verified during this build), THEN split by source so each
    # verification reaches the right classifier layer:
    #   - user/plex/series-intent → user_verifications (Layer 0; user ground
    #     truth, drives Sonarr-propagation + "awaiting sync"). Stays a
    #     _SeriesIntentLookup so the series-intent prefix fallback survives the
    #     split (intents are always user-sourced, never machine).
    #   - whisper/auto machine detect (#90) → whisper_verifications (Layer 1;
    #     overrides tags + flags mismatch, NOT user-propagation). Per-file only —
    #     machine detection never declares a series intent.
    # Splitting avoids the user layer (which runs first) grabbing a whisper row
    # and conflating machine detection with user action.
    user_verifications, verification_sources = _build_verification_lookup(
        audio_lang_store
    )

    def _is_machine(p: str) -> bool:
        s = (verification_sources.get(p) or "").lower()
        return "whisper" in s or "auto" in s

    # Machine rows are per-file entries in the lookup's base dict; pull them into
    # a plain dict, then drop them from the user lookup (its series-intent
    # fallback stays intact since intents are never machine-sourced).
    whisper_verifications: dict[str, str] = {
        p: l for p, l in user_verifications.items() if _is_machine(p)
    }
    for _p in whisper_verifications:
        user_verifications.pop(_p, None)

    items: list[CoverageItem] = []

    # Per-series srt index cache so 12 episodes of one show only walk the
    # filesystem once.
    series_srt_index: dict[str, list[str]] = {}

    # #104: pre-scan all wanted-episode series dirs in parallel (bounded)
    # up front, instead of awaiting an rglob inline one series at a time
    # inside the loop below. On a large foreign library the serialised
    # rglobs were the dominant cost of the build (minutes). The loop then
    # just reads from this index.
    _ep_canonical_dirs = [
        _strip_arr_prefix(sonarr_by_id.get(w.get("sonarrSeriesId"), {}).get("path"))
        for w in bz_eps
    ]
    series_srt_index.update(await _build_srt_index_parallel(_ep_canonical_dirs))

    # Authoritative file-path resolution via Sonarr (one episode + episodefile
    # call per series with wanted eps). Replaces fragile S<NN>E<NN> filename
    # pattern matching — catches releases that use Part.N / Episode_NN / other
    # non-canonical naming (Stanley H is the canary).
    wanted_series_ids = {w.get("sonarrSeriesId") for w in bz_eps if w.get("sonarrSeriesId")}
    sonarr_eps_by_id: dict[int, dict] = {}
    ep_file_paths: dict[int, str] = {}
    if wanted_series_ids and bundle.sonarr.is_configured():
        async def _fetch_series_files(sid: int):
            try:
                eps, files = await asyncio.gather(
                    bundle.sonarr.episodes(sid),
                    bundle.sonarr.episode_files_for_series(sid),
                    return_exceptions=False,
                )
                return sid, eps, files
            except IntegrationError as e:
                log.debug("sonarr episode lookup failed for series %s: %s", sid, e)
                return sid, [], []
        results = await asyncio.gather(*[_fetch_series_files(sid) for sid in wanted_series_ids])
        for sid, eps, files in results:
            for ep in eps:
                if isinstance(ep, dict) and "id" in ep:
                    sonarr_eps_by_id[ep["id"]] = ep
            for f in files:
                if isinstance(f, dict) and "id" in f and f.get("path"):
                    ep_file_paths[f["id"]] = f["path"]
        sources["sonarr_files"] = {"ok": True, "series": len(wanted_series_ids),
                                   "files": len(ep_file_paths)}

    # Episodes (Bazarr → Sonarr enrichment via sonarrSeriesId)
    for w in bz_eps:
        sonarr_id = w.get("sonarrSeriesId")
        s = sonarr_by_id.get(sonarr_id, {})
        canonical = _strip_arr_prefix(s.get("path"))
        if canonical and canonical not in series_srt_index:
            # #104: normally pre-populated by the parallel pre-scan above.
            # This inline fallback only fires for a dir that wasn't in the
            # pre-scan set (defensive); still offloaded so it never blocks
            # the event loop (#228).
            series_srt_index[canonical] = await asyncio.to_thread(
                _scan_for_srt_recursive, canonical
            )
        srt_paths = series_srt_index.get(canonical or "", [])
        missing_codes = [ms.get("code2") or ms.get("name") or "?"
                         for ms in (w.get("missing_subtitles") or [])]
        has_srt, srts = _stale_for_episode(
            sonarr_episode_id=w.get("sonarrEpisodeId"),
            ep_file_paths=ep_file_paths,
            sonarr_eps_by_id=sonarr_eps_by_id,
            series_srt_paths=srt_paths,
            episode_number=w.get("episode_number"),
            missing_subs=missing_codes,
        )
        item = CoverageItem(
            media_type="episode",
            title=w.get("seriesTitle") or s.get("title") or "(unknown)",
            episode_title=w.get("episodeTitle"),
            episode_number=w.get("episode_number"),
            original_language=(s.get("originalLanguage") or {}).get("name"),
            monitored=s.get("monitored"),
            tags=_tags_for(s, sonarr_tags),
            canonical_path=canonical,
            has_sub_on_disk=has_srt,
            sub_files_seen=srts,
            bazarr_sonarr_id=sonarr_id,
            bazarr_episode_id=w.get("sonarrEpisodeId"),
            missing_subtitles=[ms.get("code2") or ms.get("name") or "?"
                               for ms in (w.get("missing_subtitles") or [])],
        )
        # v1.1-B: Sonarr knows this episode has no file yet.
        if item.bazarr_episode_id and item.bazarr_episode_id in sonarr_missing_ids:
            item.pending_download = True
        # Folder-row fix: attach the actual episode-file path Sonarr already
        # resolved. canonical_path stays the series folder (the probe-match
        # search prefix); file_canonical_path is the real file so the row
        # isn't a dead folder-path and eager-probe can target it. Only set
        # when Sonarr has a file — fileless episodes stay pending_download.
        if not item.file_canonical_path:
            item.file_canonical_path = _episode_file_canonical(
                item.bazarr_episode_id, ep_file_paths, sonarr_eps_by_id,
            )
        _attach_probe_episode(item, probe_by_series_prefix,
                              tautulli_hints=activity.get("audio_lang_hints") or {},
                              user_verifications=user_verifications,
                              failed_idx=probe_failed_by_prefix,
                              plex_hints=plex_audio_hints,
                              whisper_verifications=whisper_verifications)
        _score(
            item, tt_signals,
            now_playing_titles=activity["now_playing_titles"],
            transcoding_titles=activity["transcoding_titles"],
            just_imported_eps=sonarr_recent_ids,
            airing_soon_eps=airing_soon_ids,
            ignore_forced_subtitles=ignore_forced,
        )
        items.append(item)

    # Movies (Bazarr → Radarr enrichment via title — Bazarr doesn't expose
    # radarrId in the wanted payload the same way it does sonarrSeriesId).
    for w in bz_movs:
        title = w.get("title") or w.get("movieTitle") or ""
        m = radarr_by_title.get(title.strip().lower(), {})
        canonical = _strip_arr_prefix(m.get("path"))
        # #228: iterdir on each movie folder blocks the event loop. Shallow
        # scan (one level deep) so per-call cost is small, but with 500+
        # movies the cumulative block is real. Thread it.
        if canonical:
            has_srt, srts = await asyncio.to_thread(_scan_for_srt, canonical)
        else:
            has_srt, srts = False, []
        item = CoverageItem(
            media_type="movie",
            title=title,
            original_language=(m.get("originalLanguage") or {}).get("name"),
            monitored=m.get("monitored"),
            tags=_tags_for(m, radarr_tags),
            canonical_path=canonical,
            has_sub_on_disk=has_srt,
            sub_files_seen=srts,
            bazarr_radarr_id=m.get("id"),
            missing_subtitles=[ms.get("code2") or ms.get("name") or "?"
                               for ms in (w.get("missing_subtitles") or [])],
        )
        if item.bazarr_radarr_id and item.bazarr_radarr_id in radarr_missing_ids:
            item.pending_download = True
        _attach_probe_movie(item, probe_by_series_prefix,
                            tautulli_hints=activity.get("audio_lang_hints") or {},
                            user_verifications=user_verifications,
                            failed_idx=probe_failed_by_prefix,
                            plex_hints=plex_audio_hints,
                            whisper_verifications=whisper_verifications)
        _score(
            item, tt_signals,
            now_playing_titles=activity["now_playing_titles"],
            transcoding_titles=activity["transcoding_titles"],
            just_imported_movies=radarr_recent_ids,
            ignore_forced_subtitles=ignore_forced,
        )
        items.append(item)

    # v1.1.1 #219 — Bazarr-blind defense.
    # Bazarr is structurally blind to a whole class: when a file's audio
    # metadata claims English but the series is actually foreign (encoder
    # default / mislabeled rip), Bazarr sees audio==en and treats English
    # subs as "already match audio" → never puts the episode in wanted.
    # The user has no signal, subarr's coverage was empty for these rows,
    # subgen silently skips when the user manually queues. Classic.
    #
    # Defense: for every Sonarr series with originalLanguage != English,
    # iterate its episodes, and for any episode that has a file on disk
    # but NO English sidecar sub, synthesise a coverage row flagged as
    # audio-mislabel-suspect. Bazarr-blind cases now show up in Coverage
    # with the same UI affordances as a regular wanted row.
    if bundle.sonarr.is_configured():
        items = await _add_bazarr_blind_synthetic_rows(
            bundle, sonarr_series, items,
            already_fetched_series_ids=wanted_series_ids,
            sonarr_eps_by_id=sonarr_eps_by_id,
            ep_file_paths=ep_file_paths,
            series_srt_index=series_srt_index,
            sonarr_tags=sonarr_tags,
            sonarr_missing_ids=sonarr_missing_ids,
            sonarr_recent_ids=sonarr_recent_ids,
            airing_soon_ids=airing_soon_ids,
            activity=activity,
            tt_signals=tt_signals,
            probe_by_series_prefix=probe_by_series_prefix,
            failed_idx=probe_failed_by_prefix,
            user_verifications=user_verifications,
            whisper_verifications=whisper_verifications,
            sources=sources,
            plex_hints=plex_audio_hints,
            ignore_forced_subtitles=ignore_forced,
        )

    _disqualify_unsupported(items)
    _refine_audio_sources(items, verification_sources)
    items.sort(key=lambda i: i.score, reverse=True)
    return CoverageReport(generated_at=time.time(), sources=sources, items=items)


# v1.1.1 #219 — Bazarr-blind defense pass.
async def _add_bazarr_blind_synthetic_rows(
    bundle: IntegrationBundle,
    sonarr_series: list[dict],
    items: list[CoverageItem],
    *,
    already_fetched_series_ids: set[int],
    sonarr_eps_by_id: dict[int, dict],
    ep_file_paths: dict[int, str],
    series_srt_index: dict[str, list[str]],
    sonarr_tags: dict[int, str],
    sonarr_missing_ids: set[int],
    sonarr_recent_ids: set[int],
    airing_soon_ids: set[int],
    activity: dict,
    tt_signals: dict,
    probe_by_series_prefix: dict[str, list[tuple[str, Any]]],
    failed_idx: dict[str, list] | None = None,
    user_verifications: dict[str, str],
    whisper_verifications: dict[str, str] | None = None,
    sources: dict,
    plex_hints: dict[str, str] | None = None,
    ignore_forced_subtitles: bool = False,
) -> list[CoverageItem]:
    """Build synthetic CoverageItem rows for episodes Bazarr can't see —
    foreign-language series where the file metadata lies and Bazarr's
    "audio matches subs" heuristic silently excludes them from wanted.

    Returns updated items list. Mutates `sources` to record the pass."""
    # Filter to series whose originalLanguage is set + not English.
    foreign_series = []
    for s in sonarr_series:
        if not isinstance(s, dict):
            continue
        lang = (s.get("originalLanguage") or {}).get("name") or ""
        if lang and lang.strip().lower() not in ("english", ""):
            foreign_series.append(s)
    if not foreign_series:
        sources["bazarr_blind_defense"] = {
            "ok": True, "foreign_series": 0, "synthetic_rows": 0,
            "note": "no foreign-language series in Sonarr — pass skipped",
        }
        return items

    # Fetch episodes + files for foreign series we haven't already loaded
    # (Bazarr-wanted iteration may have pre-fetched some).
    foreign_sids_to_fetch = [
        s["id"] for s in foreign_series
        if s.get("id") and s["id"] not in already_fetched_series_ids
    ]
    if foreign_sids_to_fetch:
        async def _fetch(sid: int):
            try:
                eps, files = await asyncio.gather(
                    bundle.sonarr.episodes(sid),
                    bundle.sonarr.episode_files_for_series(sid),
                )
                return sid, eps, files
            except IntegrationError as e:
                log.debug("bazarr-blind sonarr fetch failed for %s: %s", sid, e)
                return sid, [], []
        for sid, eps, files in await asyncio.gather(
            *[_fetch(sid) for sid in foreign_sids_to_fetch]
        ):
            for ep in eps:
                if isinstance(ep, dict) and "id" in ep:
                    sonarr_eps_by_id[ep["id"]] = ep
            for f in files:
                if isinstance(f, dict) and "id" in f and f.get("path"):
                    ep_file_paths[f["id"]] = f["path"]

    # Build dedup sets from existing items so we don't double-render rows
    # that already came from Bazarr wanted or other sources.
    seen_ep_ids: set[int] = {
        it.bazarr_episode_id for it in items if it.bazarr_episode_id
    }
    seen_files: set[str] = {
        it.file_canonical_path for it in items if it.file_canonical_path
    }

    # #93 perf: pre-group episodes by series id ONCE. The previous inner
    # loop scanned ALL of sonarr_eps_by_id for every foreign series — an
    # O(series × all-episodes) nested loop that, on a large foreign library
    # (~668 series × thousands of episodes), blocked the event loop for
    # 15-20s mid-refresh (the coverage-refresh freeze). Grouping makes it
    # O(episodes); behaviour is identical (same eps matched per series).
    eps_by_series_id: dict[Any, list[tuple[int, dict]]] = {}
    for _eid, _ep in sonarr_eps_by_id.items():
        eps_by_series_id.setdefault(_ep.get("seriesId"), []).append((_eid, _ep))

    # #104: pre-scan all foreign-series dirs not already in the index, in
    # parallel (bounded), before the loop. This is the ~668-series fan-out
    # that previously ran strictly one-at-a-time.
    _foreign_dirs = [
        c for c in (_strip_arr_prefix(s.get("path")) for s in foreign_series)
        if c and c not in series_srt_index
    ]
    series_srt_index.update(await _build_srt_index_parallel(_foreign_dirs))

    synthetic_added = 0
    for s in foreign_series:
        sid = s.get("id")
        series_canonical = _strip_arr_prefix(s.get("path"))
        if series_canonical and series_canonical not in series_srt_index:
            # #104: defensive inline fallback (pre-scan above normally
            # covers this). Offloaded so it never blocks the loop (#228).
            series_srt_index[series_canonical] = await asyncio.to_thread(
                _scan_for_srt_recursive, series_canonical
            )
        srt_paths = series_srt_index.get(series_canonical or "", [])
        # Iterate this series's episodes. We already collected sonarr_eps_by_id
        # for the wanted_series_ids set + foreign extras above.
        for ep_id, ep in eps_by_series_id.get(sid, []):
            if not ep.get("hasFile"):
                continue
            ep_file_id = ep.get("episodeFileId")
            if not ep_file_id:
                continue
            arr_file_path = ep_file_paths.get(ep_file_id)
            if not arr_file_path:
                continue
            file_canonical = _strip_arr_prefix(arr_file_path)
            if not file_canonical:
                continue
            if ep_id in seen_ep_ids or file_canonical in seen_files:
                continue
            # Does this file already have an English sidecar sub on disk?
            # We use the existing per-series recursive srt index — any srt
            # whose basename matches this file's stem and includes 'en' / 'eng'
            # in the lang code counts. This is intentionally conservative;
            # files with NO srt or only non-EN srt qualify as bazarr-blind.
            file_stem = file_canonical.rsplit("/", 1)[-1].rsplit(".", 1)[0]
            has_en_sidecar = any(
                _is_en_sidecar_for(srt_path, file_stem)
                for srt_path in srt_paths
            )
            if has_en_sidecar:
                continue
            # Build a tentative synthetic row + run the existing audio
            # classifier on it. The classifier reuses the same logic the
            # main coverage pipeline does (audio_langs vs originalLanguage
            # + Tautulli hints + user overrides), so we get consistent
            # judgement. AFTER classification, only keep the row if the
            # classifier judged it suspect — that's the actual bazarr-blind
            # signature. Honestly-tagged foreign audio (e.g. ger on a
            # German show) fails the suspect check and the row is dropped,
            # avoiding the false positives we saw on Ingo Thiel.
            item = CoverageItem(
                media_type="episode",
                title=s.get("title") or "(unknown)",
                episode_title=ep.get("title"),
                # Bazarr-format "1x3" so _episode_filename_pattern can
                # parse it and find the probe entry for this episode's
                # file. (The to_dict layer renders S01E02 in the UI.)
                episode_number=(
                    f"{ep.get('seasonNumber')}x{ep.get('episodeNumber')}"
                    if ep.get("seasonNumber") is not None
                    and ep.get("episodeNumber") is not None
                    else None
                ),
                original_language=(s.get("originalLanguage") or {}).get("name"),
                monitored=s.get("monitored"),
                tags=_tags_for(s, sonarr_tags),
                canonical_path=series_canonical,
                file_canonical_path=file_canonical,
                has_sub_on_disk=False,  # we just confirmed no EN sidecar
                sub_files_seen=[],
                bazarr_sonarr_id=sid,
                bazarr_episode_id=ep_id,
                missing_subtitles=["en"],   # treat as needing English
                # Suspect flags get set AFTER _classify_audio_label below
                # has the chance to inspect audio_langs from the probe.
                # Setting them upfront would bias every foreign-language
                # episode into the bazarr-blind bucket regardless of
                # whether its metadata is actually lying.
            )
            # Run the normal probe + classifier passes. _classify_audio_label
            # sets audio_label_suspect=True ONLY when audio metadata
            # actually looks mislabeled (claims English / und on a foreign
            # show). If the audio is honestly tagged foreign, suspect
            # stays False — and we drop the synthetic row entirely. Those
            # rows are regular foreign-language coverage scenarios Bazarr
            # can handle on its own; they don't need our special chip.
            _attach_probe_episode(
                item, probe_by_series_prefix,
                tautulli_hints=activity.get("audio_lang_hints") or {},
                user_verifications=user_verifications,
                failed_idx=failed_idx,
                plex_hints=plex_hints,
                whisper_verifications=whisper_verifications,
            )
            # Bazarr-blind requires positive evidence the file is not
            # what Bazarr thinks it is. Two ways to get there:
            #   (a) classifier set suspect=True — audio claims English
            #       on a foreign series (the unverified mislabel case)
            #   (b) user verified the file as a foreign language but
            #       file metadata STILL says English on disk — Bazarr
            #       can't read user verifications, only file metadata,
            #       so Bazarr is STILL blind even though we now know
            #       the truth. Keep surfacing so the user knows the gap
            #       still exists at the Bazarr level.
            user_lang = (
                user_verifications.get(file_canonical) if user_verifications else None
            )
            user_confirmed_foreign = (
                user_lang and user_lang.strip().lower() not in ("", "en", "eng")
            )
            if not item.audio_label_suspect and not user_confirmed_foreign:
                continue
            # Earned the suspect signal — mark it explicitly + add the
            # upstream-fix note that's specific to this defense.
            item.bazarr_blind = True
            item.audio_label_notes.append(
                f"Bazarr-blind: Sonarr originalLanguage="
                f"{(s.get('originalLanguage') or {}).get('name')!r}. "
                "Fix at source by editing the series Language Profile in Sonarr."
            )
            _score(
                item, tt_signals,
                now_playing_titles=activity["now_playing_titles"],
                transcoding_titles=activity["transcoding_titles"],
                just_imported_eps=sonarr_recent_ids,
                airing_soon_eps=airing_soon_ids,
                ignore_forced_subtitles=ignore_forced_subtitles,
            )
            items.append(item)
            seen_ep_ids.add(ep_id)
            seen_files.add(file_canonical)
            synthetic_added += 1

    sources["bazarr_blind_defense"] = {
        "ok": True,
        "foreign_series": len(foreign_series),
        "synthetic_rows": synthetic_added,
    }
    log.info(
        "bazarr-blind defense: added %d synthetic rows across %d foreign-language series",
        synthetic_added, len(foreign_series),
    )
    return items


def _audio_metadata_looks_mislabeled(audio_langs: list[str] | None) -> bool:
    """The Bazarr-blind signature: file's audio metadata claims English
    OR is undetected, on a series Sonarr knows is foreign-language.
    `None` (no probe data) is treated as 'insufficient evidence'."""
    if audio_langs is None:
        return False
    # [#118] Normalize to ISO-639-1 so eng/en-US collapse to 'en' — otherwise a
    # region-tagged English track on a foreign show slips the mislabel check.
    from .langs import normalize_lang
    norm = [normalize_lang(l) or "und" for l in audio_langs]
    if not norm:
        # Empty audio_langs list = probe ran but found nothing → undetected,
        # which IS a bazarr-blind candidate (Bazarr also has nothing to go on).
        return True
    # Mislabeled signature: every detected track is English OR und.
    non_und = [l for l in norm if l not in ("", "und")]
    if not non_und:
        # All und → undetected, treat as candidate.
        return True
    return all(l == "en" for l in non_und)  # norm is ISO-639-1


def _is_en_sidecar_for(srt_path: str, file_stem: str) -> bool:
    """True if `srt_path` looks like an English sidecar for the video whose
    stem (filename minus extension) is `file_stem`. Tolerates Plex-style
    naming (<stem>.en.srt, <stem>.eng.srt) plus engine-suffix variants
    (<stem>.en.alass.srt, etc) since subsyncarr produces multiples."""
    name = srt_path.rsplit("/", 1)[-1]
    if not name.endswith(".srt"):
        return False
    base = name[:-4]
    if not base.startswith(file_stem):
        return False
    tail = base[len(file_stem):]
    if not tail.startswith("."):
        return False
    parts = [p for p in tail.split(".") if p]
    # Any token equal to en/eng marks it English.
    return any(p.lower() in ("en", "eng") for p in parts)
