"""Mode A delivery (spec §2.5): generate the exact config text the user
applies. Pure string templates — no I/O, no docker writes (mode B was
explicitly rejected: subarr never edits the host's Docker config).

The generated artifacts deliberately set ONLY the hardware-dependent vars
(WHISPER_MODEL / TRANSCRIBE_DEVICE / COMPUTE_TYPE). The tuned kwargs +
regroup are baked in the r9 image and must not be duplicated here — a
duplicated value would pin the user to today's tuning and mask image
default upgrades.
"""

from __future__ import annotations

from textwrap import dedent, indent


def generate_env_additions(*, model: str, device: str, compute_type: str) -> str:
    """The three lines to add under an existing subgen service's
    `environment:` mapping."""
    return dedent(f"""\
        # guided subgen setup — hardware-matched (generated by subarr)
        WHISPER_MODEL: {model}
        TRANSCRIBE_DEVICE: {device}
        COMPUTE_TYPE: {compute_type}
    """)


_GPU_BLOCK = """\
deploy:
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: 1
          capabilities: [gpu]
"""


def generate_full_compose(
    *,
    model: str,
    device: str,
    compute_type: str,
    media_host_path: str,
    port: int = 9000,
    gpu: bool,
) -> str:
    """Greenfield subarr-subgen compose for the no-subgen-yet user."""
    env_block = indent(
        generate_env_additions(model=model, device=device, compute_type=compute_type).rstrip(),
        "      ",
    )
    parts = [
        "services:",
        "  subgen:",
        "    image: ghcr.io/coaxk/subarr-subgen:latest",
        "    container_name: subgen",
        "    restart: unless-stopped",
        "    ports:",
        f'      - "{port}:9000"',
        "    environment:",
        "      TZ: Etc/UTC",
        env_block,
        "    volumes:",
        "      - ./subgen/models:/subgen/models",
        f"      - {media_host_path}:/media",
    ]
    if gpu:
        parts.append(indent(_GPU_BLOCK.rstrip(), "    "))
    return "\n".join(parts) + "\n"


def detection_passthrough_snippet() -> str:
    """The optional-but-recommended utility-only GPU passthrough for the
    SUBARR container (spec §2.1): lets subarr query the card (nvidia-smi)
    without reserving any VRAM/compute from subgen."""
    return dedent("""\
        # add under subarr's service to enable automatic GPU detection
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [utility]
    """)
