-- 031_pr451_text_lang_check.sql
--
-- #451: persist ONE bounded advisory text-LID checker result on the aftercare
-- result row (the just-completed job's signal/result model). Mirrors the
-- readability_json / signals_json pattern: a single TEXT column holding the
-- checker's bounded to_dict() — status, reason, normalized languages, bounded
-- evidence, provenance state, checker/policy version, probabilities. NEVER
-- full subtitle text.
--
-- Advisory only: this column NEVER gates completion, upload, provider
-- selection, OCR, or HI policy. It is NULL until a check lands (legacy rows and
-- jobs still in flight stay NULL = "no check"). The checker runs asynchronously
-- after the aftercare row is recorded, so it is written by a follow-up UPDATE
-- (AfterCareStore.set_text_lang_check) rather than the initial INSERT.
ALTER TABLE aftercare_results ADD COLUMN text_lang_check_json TEXT;
